# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cba/CbaMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cba/CbaMessage.proto',
  package='cba',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x63\x62\x61/CbaMessage.proto\x12\x03\x63\x62\x61\"\xe5\x02\n\nCbaMessage\x12\x13\n\x0bmessageType\x18\x01 \x01(\t\x12\x0f\n\x07groupID\x18\x02 \x01(\t\x12\x11\n\tprocessID\x18\x03 \x01(\t\x12\x11\n\tsessionID\x18\x04 \x01(\t\x12\x13\n\x0b\x63reatedTime\x18\x05 \x01(\x03\x12\x12\n\neffectTime\x18\x06 \x01(\x03\x12\x12\n\nexpireTime\x18\x07 \x01(\x03\x12\x17\n\x0ftimeOutResponse\x18\x08 \x01(\x03\x12\x16\n\x0etimeOutProcess\x18\t \x01(\x03\x12\x15\n\rmessageNumber\x18\n \x01(\x05\x12\x12\n\nisFinished\x18\x0b \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x0c \x01(\t\x12-\n\x07\x63ontent\x18\r \x03(\x0b\x32\x1c.cba.CbaMessage.ContentEntry\x1a.\n\x0c\x43ontentEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)




_CBAMESSAGE_CONTENTENTRY = _descriptor.Descriptor(
  name='ContentEntry',
  full_name='cba.CbaMessage.ContentEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cba.CbaMessage.ContentEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='cba.CbaMessage.ContentEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=387,
)

_CBAMESSAGE = _descriptor.Descriptor(
  name='CbaMessage',
  full_name='cba.CbaMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageType', full_name='cba.CbaMessage.messageType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groupID', full_name='cba.CbaMessage.groupID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processID', full_name='cba.CbaMessage.processID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessionID', full_name='cba.CbaMessage.sessionID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdTime', full_name='cba.CbaMessage.createdTime', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='effectTime', full_name='cba.CbaMessage.effectTime', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expireTime', full_name='cba.CbaMessage.expireTime', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeOutResponse', full_name='cba.CbaMessage.timeOutResponse', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeOutProcess', full_name='cba.CbaMessage.timeOutProcess', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageNumber', full_name='cba.CbaMessage.messageNumber', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isFinished', full_name='cba.CbaMessage.isFinished', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='cba.CbaMessage.description', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='cba.CbaMessage.content', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CBAMESSAGE_CONTENTENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=387,
)

_CBAMESSAGE_CONTENTENTRY.containing_type = _CBAMESSAGE
_CBAMESSAGE.fields_by_name['content'].message_type = _CBAMESSAGE_CONTENTENTRY
DESCRIPTOR.message_types_by_name['CbaMessage'] = _CBAMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CbaMessage = _reflection.GeneratedProtocolMessageType('CbaMessage', (_message.Message,), dict(

  ContentEntry = _reflection.GeneratedProtocolMessageType('ContentEntry', (_message.Message,), dict(
    DESCRIPTOR = _CBAMESSAGE_CONTENTENTRY,
    __module__ = 'cba.CbaMessage_pb2'
    # @@protoc_insertion_point(class_scope:cba.CbaMessage.ContentEntry)
    ))
  ,
  DESCRIPTOR = _CBAMESSAGE,
  __module__ = 'cba.CbaMessage_pb2'
  # @@protoc_insertion_point(class_scope:cba.CbaMessage)
  ))
_sym_db.RegisterMessage(CbaMessage)
_sym_db.RegisterMessage(CbaMessage.ContentEntry)


_CBAMESSAGE_CONTENTENTRY.has_options = True
_CBAMESSAGE_CONTENTENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
