class Constant:

    message_type_online_request = "1"
    message_type_online_response = "2"
    message_type_online_status = "3"
    message_type_online_warning = "4"
    message_type_offline_request = "1001"
    message_type_offline_response = "1002"
    message_type_offline_status = "1003"
    message_type_offline_warning = "1004"

    group_id_cba360 = "cba360"
    group_id_preprocessing = "preprocessing"
    group_id_segmentation = "segmentation"
    group_id_inactive = "inactive"
    group_id_recommender = "recommender"
    group_id_campaign = "campaign"

    process_id_accum = "accum"
    process_id_query = "query"
    process_id_filter = "filter_segment"
    process_id_recommender_pre = "recommender_preprocessing"
    process_id_inactive_pre = "inactive_preprocessing"
    process_id_inactive_sample = "inactive_sampling"
    process_id_segment = "segment"
    process_id_inactive_training = "inactive_training"
    process_id_inactive_deploy = "inactive_deploy"
    process_id_inactive_predict = "inactive_predict"
    process_id_inactive_evaluate = "inactive_evaluate"
    process_id_recommender_training = "recommender_training"
    process_id_recommender_deploy = "recommender_deploy"
    process_id_recommender_predict = "recommender_predict"
    process_id_recommender_evaluate = "recommender_evaluate"
    process_id_creation = "creation"
    process_id_execution = "execution"
    process_id_interation = "interation"
    process_id_evaluation = "evaluation"
    process_id_visualization = "visualization"

    status_accepted = "ACCEPTED"
    status_running = "RUNNING"
    status_finished = "FINISHED"

    topic_process_status = "cba_process_status"
    topic_request = "cba_request"
    topic_response = "cba_response"
